- object name: camera
  settings:
    - name: hardware brightness
      value: -0.3600000000000004
    - name: hardware contrast
      value: 1
    - name: hardware exposure
      value: -1
    - name: hardware gain
      value: -1
    - name: hardware hue
      value: 0.5600000000000001
    - name: hardware saturation
      value: 1
    - name: software brightness
      value: 1
    - name: software contrast
      value: 1

- object name: object_track
  settings:
    - name: max_obj_size
      value: 319
    - name: min_obj_size
      value: 14
    - name: max_h
      value: 1
    - name: max_s
      value: 251
    - name: max_v
      value: 255
    - name: min_h
      value: 0
    - name: min_s
      value: 250
    - name: min_v
      value: 54

